export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"

  | "Ghidra"

  | "ROS"
  | "3D Printing"
  | "C/C++"
  | "Gazebo"
  | "SolidWorks"
  | "Fusion 360"
  | "AutoCAD"
  | "Dassault Systèmes CATIA"
  | "Assembly Design"
  | "Gear-Driven Transmission"
  | "CoreXY Kinematics"
  | "PID Control"
  | "SLAM"
  | "Path Planning"
  | "Tkinter"
  | "Technical Research Writing"
  | "MATLAB"
  | "Simulink"
  | "Arduino"
  | "Raspberry Pi"
  | "ROS2"
  | "Wireless Communication"
  | "Mobile Robots"
  | "Multi-Robot Systems"
  | "OpenCV"
  | "MoveIt!"
  | "STM32"
  | "UART/Serial Communication"
  | "Cloud Dashboard"
  | "Circuit Design"
  | "Sensor Fusion"
  | "Arduino IDE"
  | "Webots"
  | "Kinematic Simulation"
  | "Fabrication"
  | "Interdisciplinary Workflow Management"
  | "Hardware Integration & Troubleshooting";

export type ValidCategory =
  | "Interdisciplinary Coordination"
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Data Science"
  | "Mobile Dev"
  | "3D Modeling"
  | "Machine Learning"
  | "AI"
  | "IoT Systems"
  | "Embedded Systems"
  | "Control Systems"
  | "Computer Vision"
  | "Human-Machine Interface"
  | "Hardware Integration"
  | "Robotics"
  | "ROS"
  | "Mechatronics"
  | "Mechanical Design"
  | "CAD Design"
  | "Research"
  | "Internship"
  | "Freelance"
  | "Personal Project"
  | "Algorithm"
  | "Team Leadership"
  | "Competition";

export type ValidExpType = "Personal" | "Professional" | "Competition";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "resume"
;
